version: '3'

services:

  webimage:
    build:
      context: .
      dockerfile: Dockerfile
    image: webimage
    container_name: webcontainer
    restart: unless-stopped
    ports:
      - "8080:80"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - webimage
    command: certonly --webroot --webroot-path=/var/www/html --email artem@merets.ru --agree-tos --no-eff-email -d appsec.team  -d www.appsec.team

volumes:
  certbot-etc:
  certbot-var:
