version: '3.4'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      network: host
      args:
        - CERTBOT_EMAIL=artem@merets.ru
        - DOMAIN_LIST=appsec.team,www.appsec.team
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
volumes:
  letsencrypt:
